package org.wecancodeit.com.project;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.wecancodeit.com.project.Model.ContinentModel;
import org.wecancodeit.com.project.Model.CountryModel;
import org.wecancodeit.com.project.Model.IslandChainModel;
import org.wecancodeit.com.project.Model.WaterBodyModel;
import org.wecancodeit.com.project.Repo.ContinentRepo;
import org.wecancodeit.com.project.Repo.CountryRepo;
import org.wecancodeit.com.project.Repo.IslandChainRepo;
import org.wecancodeit.com.project.Repo.WaterBodyRepo;
import org.wecancodeit.com.project.Model.*;
import org.wecancodeit.com.project.Repo.*;

import javax.annotation.Resource;

@Component
public class Populator implements CommandLineRunner {

    @Resource
    private ContinentRepo continentRepo;

    @Resource
    private CountryRepo countryRepo;

    @Resource
    private WaterBodyRepo waterBodyRepo;

    @Resource
    private IslandChainRepo islandChainRepo;

    @Resource
    private ItineraryRepo itineraryRepo;

    @Resource
    private PackListRepo packListRepo;

    @Override
    public void run(String... args) throws Exception {

        // Packing List
        PackListModel packList1 = new PackListModel("Tent", "Hiking Backpack", "Summer sleeping bag", "Insect repellent wristband", "Travel hammock");
        packListRepo.save(packList1);

        PackListModel packList2 = new PackListModel("Sunglasses", "Waterproof watch", "Bathing suits", "Raincoat / Poncho", "Comfortable Open Shoes");
        packListRepo.save(packList2);

        PackListModel packList3 = new PackListModel("Sun Hat", "Waterproof Footwear", "Flotation Strap", "Bug repellent", "Sunscreen lotion");
        packListRepo.save(packList3);

        PackListModel packList4 = new PackListModel("Activated Charcoal", "Hand Sanitizer", "Beach Towel", "Sun Tan Lotion", "Offline Map App");
        packListRepo.save(packList4);

        PackListModel packList5 = new PackListModel("Snorkel", "Waterproof Speakers", "Toothbrush Cover", "Waterproof Money Pouch", "Underwater Camera");
        packListRepo.save(packList5);


        // Itinerary
        ItineraryModel bassIslandsItinerary = new ItineraryModel("Day 1:", "Snorkeling", "Day 2:", "Sky Diving", "Day 3:", "Food Exploration");
        itineraryRepo.save(bassIslandsItinerary);

        ItineraryModel andamanIslandsItinerary = new ItineraryModel("Day 1:","Scuba Diving in Havlock","Day 2:","Night Mangroves Kayaking","Day 3:","Hinterland Cycling Tour");
        itineraryRepo.save(andamanIslandsItinerary);

        ItineraryModel bermudaIslandsItinerary = new ItineraryModel("Day 1:","Bermuda Catamaran Sail and Snorkel Tour","Day 2:","Bermuda Aquarium and Crystal Caves","Day 3:","Bermuda Food Tour");
        itineraryRepo.save(bermudaIslandsItinerary);

        ItineraryModel balearicIslandsItinerary = new ItineraryModel("Day 1:","Cala Canta and Cala Bassa Beach Cruise with Paddle Surf","Day 2:","Buggy Discover Tour","Day 3:","Small-Group Cava de Coloms Sea Caving Tour");
        itineraryRepo.save(balearicIslandsItinerary);

        ItineraryModel caboVerdeIslandsItinerary = new ItineraryModel("Day 1:","Snorkeling","Day 2:","Sky Diving","Day 3:","Hiking");
        itineraryRepo.save(caboVerdeIslandsItinerary);

        ItineraryModel capriIslandsItinerary = new ItineraryModel("Day 1:","Capri and Blue Grotto Day Tour","Day 2:","Boat Excursion","Day 3:","Snorkeling");
        itineraryRepo.save(capriIslandsItinerary);

        ItineraryModel chiloeIslandsItinerary = new ItineraryModel("Day 1:","Penguins of Punihuil-Ancud City","Day 2:","Tocoihue Waterfall in Chiloe","Day 3:","Bosque Piedra Reserve Tour");
        itineraryRepo.save(chiloeIslandsItinerary);

        ItineraryModel corfuIslandsItinerary = new ItineraryModel("Day 1","Corfu Private Yacht Club","Day 2","Quad ATV Safari Guided Tour","Day 3:","e-MTB Private Tour - Korakiana Village 40Km");
        itineraryRepo.save(corfuIslandsItinerary);

        ItineraryModel basicItinerary = new ItineraryModel("Day 1:","Deep Sea Diving","Day 2","Boat Ride","Day 3:","Swimming with Dolphins");
        itineraryRepo.save(basicItinerary);

        ItineraryModel genericItinerary = new ItineraryModel("Day 1:","ATV","Day 2:","Outdoor Ziplining","Day 3:","Snorkeling");
        itineraryRepo.save(genericItinerary);

        // Continents
        ContinentModel africa = new ContinentModel("Africa", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#0.95/12.3/-14");
        ContinentModel asia = new ContinentModel("Asia", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#1.49/37.4/87.3");
        ContinentModel australia = new ContinentModel("Australia", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#2.12/-24.53/133.78");
        ContinentModel europe = new ContinentModel("Europe", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#0.81/-6.6/-65.1");
        ContinentModel northAmerica = new ContinentModel("North America", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#0.96/55.9/-109.8");
        ContinentModel southAmerica = new ContinentModel("South America", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#1.88/-24.14/-60.39");
        continentRepo.save(africa);
        continentRepo.save(asia);
        continentRepo.save(australia);
        continentRepo.save(europe);
        continentRepo.save(northAmerica);
        continentRepo.save(southAmerica);


        // Countries
        CountryModel australiaCountry = new CountryModel("Australia", australia, "Australia, officially the Commonwealth of Australia, is a sovereign country comprising the mainland of the Australian continent, the island of Tasmania, and numerous smaller islands. With an area of 7,617,930 square kilometres, Australia is the largest country by area in Oceania and the world's sixth-largest country.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#2.12/-24.53/133.78");
        CountryModel brazil = new CountryModel("Brazil", southAmerica, "Brazil, officially the Federative Republic of Brazil, is the largest country in both South America and Latin America. At 8.5 million square kilometers and with over 211 million people, Brazil is the world's fifth-largest country by area and the sixth most populous.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#2.86/-12.36/-51.84");
        CountryModel canada = new CountryModel("Canada", northAmerica, "Canada is a country in North America. Its ten provinces and three territories extend from the Atlantic to the Pacific and northward into the Arctic Ocean, covering 9.98 million square kilometers, making it the world's second-largest country by total area.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#1.92/62.25/-104.15");
        CountryModel chile = new CountryModel("Chile", southAmerica, "Chile is a long, narrow country stretching along South America's western edge, with more than 6,000km of Pacific Ocean coastline. Santiago, its capital, sits in a valley surrounded by the Andes and Chilean Coast Range mountains. The city's palm-lined Plaza de Armas contains the neoclassical cathedral and the National History Museum. The massive Parque Metropolitano offers swimming pools, a botanical garden and zoo.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.31/-28.18/-69.1");
        CountryModel colombia = new CountryModel("Colombia", southAmerica, "Colombia, officially the Republic of Colombia, is a transcontinental country spanning South America and an insular region in North America.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.75/2.69/-72.71");
        CountryModel croatia = new CountryModel("Croatia", europe, "Croatia, officially the Republic of Croatia, is a country at the crossroads of Central and Southeast Europe on the Adriatic Sea.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.19/43.84/18.31");
        CountryModel ecuador = new CountryModel("Ecuador", southAmerica, "Ecuador is a country straddling the equator on South America’s west coast. Its diverse landscape encompasses Amazon jungle, Andean highlands and the wildlife-rich Galápagos Islands. In the Andean foothills at an elevation of 2,850m, Quito, the capital, is known for its largely intact Spanish colonial center, with decorated 16th- and 17th-century palaces and religious sites, like the ornate Compañía de Jesús Church.", " https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#4.43/-0.15/-77.89");
        CountryModel greece = new CountryModel("Greece", europe, "Greece is a country in southeastern Europe with thousands of islands throughout the Aegean and Ionian seas. Influential in ancient times, it's often called the cradle of Western civilization. Athens, its capital, retains landmarks including the 5th-century B.C. Acropolis citadel with the Parthenon temple. Greece is also known for its beaches, from the black sands of Santorini to the party resorts of Mykonos. Greece is a country in southeastern Europe with thousands of islands throughout the Aegean and Ionian seas. Influential in ancient times, it's often called the cradle of Western civilization. Athens, its capital, retains landmarks including the 5th-century B.C. Acropolis citadel with the Parthenon temple. Greece is also known for its beaches, from the black sands of Santorini to the party resorts of Mykonos.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#5.62/38.982/22.753");
        CountryModel india = new CountryModel("India", asia, "India, officially the Republic of India, is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#2.96/22.95/80.05");
        CountryModel italy = new CountryModel("Italy", europe, "Italy, a European country with a long Mediterranean coastline, has left a powerful mark on Western culture and cuisine. Its capital, Rome, is home to the Vatican as well as landmark art and ancient ruins. Other major cities include Florence, with Renaissance masterpieces such as Michelangelo’s David and Brunelleschi's Duomo; Venice, the city of canals; and Milan, Italy’s fashion capital.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=false&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=false#4.25/41.28/14.05");
        CountryModel madagascarCountry = new CountryModel("Madagascar", africa, "Madagascar, officially the Republic of Madagascar, and previously known as the Malagasy Republic, is an island country in the Indian Ocean, approximately 400 kilometres off the coast of East Africa across the Mozambique Channel.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#4.61/-19.14/46.74");
        CountryModel philippinesCountry = new CountryModel("Philippines", asia, "For God, People, Nature, and Country", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#4.26/12.04/123.51");
        CountryModel republicOfCaboVerde = new CountryModel("Republic of Cabo Verde", africa, "Cape Verde or Cabo Verde, officially the Republic of Cabo Verde, is an archipelago and island country in the central Atlantic Ocean, consisting of ten volcanic islands with a combined land area of about 4,033 square kilometres.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.65/16.94/-25.01");
        CountryModel republicOfSeychelles = new CountryModel("Republic Of Seychelles", africa, "The Seychelles is an archipelago of 115 islands in the Indian Ocean, off East Africa. It's home to numerous beaches, coral reefs and nature reserves, as well as rare animals such as giant Aldabra tortoises. Mahé, a hub for visiting the other islands, is home to capital Victoria. It also has the mountain rainforests of Morne Seychellois National Park and beaches, including Beau Vallon and Anse Takamaka. ", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#4.92/-6.91/52.37");
        CountryModel spain = new CountryModel("Spain", europe, "Spain, a country on Europe’s Iberian Peninsula, includes 17 autonomous regions with diverse geography and cultures. Capital city Madrid is home to the Royal Palace and Prado museum, housing works by European masters. Segovia has a medieval castle (the Alcázar) and an intact Roman aqueduct. Catalonia’s capital, Barcelona, is defined by Antoni Gaudí’s whimsical modernist landmarks like the Sagrada Família church.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.5/40.47/-3.49");
        CountryModel tanzania = new CountryModel("Tanzanian", africa, "Tanzania is an East African country known for its vast wilderness areas. They include the plains of Serengeti National Park, a safari mecca populated by the “big five” game (elephant, lion, leopard, buffalo, rhino), and Kilimanjaro National Park, home to Africa’s highest mountain. Offshore lie the tropical islands of Zanzibar, with Arabic influences, and Mafia, with a marine park home to whale sharks and coral reefs.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.43/-5.92/33.81");
        CountryModel thailand = new CountryModel("Thailand", asia, "Thailand is a Southeast Asian country. It's known for tropical beaches, opulent royal palaces, ancient ruins and ornate temples displaying figures of Buddha. In Bangkok, the capital, an ultramodern cityscape rises next to quiet canalside communities and the iconic temples of Wat Arun, Wat Pho and the Emerald Buddha Temple (Wat Phra Kaew). Nearby beach resorts include bustling Pattaya and fashionable Hua Hin.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.66/14.61/102.17");
        CountryModel uk = new CountryModel("United Kingdom", europe, "The Queen lives here.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#3.7/55.08/-4.72");
        CountryModel usa = new CountryModel("United States of America", northAmerica, "The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles' Hollywood is famed for filmmaking.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#1.83/39.41/-97.13");
        countryRepo.save(australiaCountry);
        countryRepo.save(brazil);
        countryRepo.save(canada);
        countryRepo.save(chile);
        countryRepo.save(colombia);
        countryRepo.save(croatia);
        countryRepo.save(ecuador);
        countryRepo.save(greece);
        countryRepo.save(india);
        countryRepo.save(italy);
        countryRepo.save(madagascarCountry);
        countryRepo.save(philippinesCountry);
        countryRepo.save(republicOfCaboVerde);
        countryRepo.save(republicOfSeychelles);
        countryRepo.save(spain);
        countryRepo.save(tanzania);
        countryRepo.save(thailand);
        countryRepo.save(uk);
        countryRepo.save(usa);


        //Water Bodies
        WaterBodyModel adriaticSea = new WaterBodyModel("Adriatic Sea", "The Adriatic Sea is a body of water separating the Italian Peninsula from the Balkans. The Adriatic is the northernmost arm of the Mediterranean Sea, extending from the Strait of Otranto to the northwest and the Po Valley.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#5.4/42.913/16.022");
        WaterBodyModel aegeanSea = new WaterBodyModel("Aegean Sea", "The Aegean Sea is an elongated embayment of the Mediterranean Sea between Europe and Asia. It is located between the Balkans and Anatolia, and covers an area of some 215,000 square kilometres", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#5.31/38.482/25.269");
        WaterBodyModel andamanSea = new WaterBodyModel("Andaman Sea", "The Andaman Sea is a marginal sea of the northeastern Indian Ocean bounded by the coastlines of Myanmar and Thailand along the Gulf of Martaban and west side of the Malay Peninsula, and separated from the Bay of Bengal to its west by the Andaman Islands and the Nicobar Islands.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#5.35/11.412/95.969");
        WaterBodyModel atlanticOcean = new WaterBodyModel("Atlantic Ocean", "The Atlantic Ocean is the second-largest of the world's five oceans, with an area of about 106,460,000 km². It covers approximately 20% of Earth's surface and about 29% of its water surface area.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#1.24/3/-25.6");
        WaterBodyModel caribbeanSea = new WaterBodyModel("Caribbean", "The Caribbean Islands is a massive archipelago located in the Caribbean Sea, that can be subdivided into a few different regions: the Lucayan Archipelago, the Greater Antilles, the Lesser Antilles and the ABC Islands. There are 13 sovereign states and 17 dependent territories in the Caribbean, and the predominant languages are English, Spanish, French, Dutch and Antillean creole. The Caribbean sprawls across more than 1.06 million square miles and is primarily located between North America and South America.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#3.2/19.34/-71.64");
        WaterBodyModel gulfOfThailand = new WaterBodyModel("Gulf of Thailand", "The Gulf of Thailand, also known as the Gulf of Siam, is a shallow inlet in the southwestern South China Sea, bounded between the southwestern shores of the Indochinese Peninsula and the northern half of the Malay Peninsula.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#5.42/9.591/101.992");
        WaterBodyModel indianOcean = new WaterBodyModel("Indian Ocean", "The Indian Ocean has been known by its present name since at least 1515 when the Latin form Oceanus Orientalis Indicus (\"Indian Eastern Ocean\") is attested, named for India, which projects into it. It was earlier known as the Eastern Ocean, a term that was still in use during the mid-18th century (see map), as opposed to the Western Ocean (Atlantic) before the Pacific was surmised.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#1.66/-3.7/74.7");
        WaterBodyModel ionianSea = new WaterBodyModel("Ionian Sea", "The Ionian Sea is an elongated bay of the Mediterranean Sea. It is connected to the Adriatic Sea to the north, and is bounded by Southern Italy, including Calabria, Sicily, and the Salento peninsula to the west, southern Albania to the north, and the west coast of Greece, including the Peloponnese.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#5.43/38.797/19.173");
        WaterBodyModel jintotoloChannel = new WaterBodyModel("Jintotolo Channel", "The Jintotolo Channel is the body of water that connects the Sibuyan Sea with the Visayan Sea. It is located between the Philippine islands of Panay and Masbate, and is an important shipping route to and from the Central Visayas.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.98/11.5697/123.2154");
        WaterBodyModel lakeErie = new WaterBodyModel("Lake Erie", "A place where time moves a little slower, loved ones feel a little closer and there's a Great Lake between you and your worries. From island hopping to birdwatching, record-breaking roller coasters to water parks, wineries to dockside dining, plus hidden gems that keep the fun going all year long. However you like to coast – you'll find it here.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#5.49/42.268/-80.862\n");
        WaterBodyModel mediterraneanSea = new WaterBodyModel("Mediterranean Sea", "The Mediterranean Sea is a sea connected to the Atlantic Ocean, surrounded by the Mediterranean Basin and almost completely enclosed by land: on the north by Western and Southern Europe and Anatolia, on the south by North Africa, and on the east by the Levant.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#4.67/34.29/23.75");
        WaterBodyModel pacificOcean = new WaterBodyModel("Pacific Ocean", "The Pacific Ocean is the largest and deepest of Earth's five oceanic divisions. It extends from the Arctic Ocean in the north to the Southern Ocean in the south and is bounded by the continents of Asia and Australia in the west and the Americas in the east.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#1.12/3.1/-155.5");
        WaterBodyModel sargassoSea = new WaterBodyModel("Sargasso Sea", "The Aegean Sea is an elongated embayment of the Mediterranean Sea between Europe and Asia", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#9/37.78/-122.4241");
        WaterBodyModel southAtlanticOcean = new WaterBodyModel("South Atlantic", "The Atlantic Ocean is the second-largest of the world's five oceans, with an area of about 106,460,000 km². It covers approximately 20% of Earth's surface and about 29% of its water surface area.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#1.42/-27.7/-15.6");
        WaterBodyModel southChinaSea = new WaterBodyModel("South China Sea", "The South China Sea Islands consist of over 250 islands, atolls, cays, shoals, reefs and seamounts in the South China Sea. The islands are mostly low and small, and have few inhabitants. The islands and surrounding seas are subject to overlapping territorial claims by the countries bordering the South China Sea. The South China Sea Islands constitute a distinct tropical moist broadleaf forest terrestrial ecoregion, and the South China Sea Oceanic Islands marine ecoregion.", "https://api.mapbox.com/styles/v1/missmadisonrose/ckxpgq7sq0iqt14piwva3j92k.html?title=false&access_token=pk.eyJ1IjoibWlzc21hZGlzb25yb3NlIiwiYSI6ImNreHBmd2JpZjd0ZGwydXEzMTZrMThjcXQifQ.Ubq6kw0wIFtQMKZunE0gyg&zoomwheel=false#3.01/5.82/113.71");
        WaterBodyModel tyrrhenianSea = new WaterBodyModel("Tyrrhenian Sea", "The Tyrrhenian Sea is part of the Mediterranean Sea off the western coast of Italy. It is named for the Tyrrhenian people identified with the Etruscans of Italy.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#5.19/39.451/13.06");
        waterBodyRepo.save(adriaticSea);
        waterBodyRepo.save(aegeanSea);
        waterBodyRepo.save(andamanSea);
        waterBodyRepo.save(atlanticOcean);
        waterBodyRepo.save(caribbeanSea);
        waterBodyRepo.save(gulfOfThailand);
        waterBodyRepo.save(indianOcean);
        waterBodyRepo.save(ionianSea);
        waterBodyRepo.save(jintotoloChannel);
        waterBodyRepo.save(lakeErie);
        waterBodyRepo.save(mediterraneanSea);
        waterBodyRepo.save(pacificOcean);
        waterBodyRepo.save(sargassoSea);
        waterBodyRepo.save(southAtlanticOcean);
        waterBodyRepo.save(southChinaSea);
        waterBodyRepo.save(tyrrhenianSea);


        //Island Chains
        IslandChainModel andamanIsland = new IslandChainModel("Andaman Islands", india, indianOcean, andamanIslandsItinerary, bassIslandsPackList, "Sparsely-populated beaches that give way to an ocean brimming with interesting marine life and coral gardens are just one of the reasons to visit the beautiful Andaman and Nicobar Islands. Ghandi Park, Sippighat Farm and the century-old Cellular Jail (now a pilgrimage destination) provide glimpses into the past and present of these peaceful islands with a mysterious and multicultural past.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.36/11.858/92.75");
        IslandChainModel balearicIsland = new IslandChainModel("Balearic Islands", spain, ionianSea, balearicIslandsItinerary, bassIslandsPackList, "The brightest stars of Los Baleares are Majorca, Ibiza and peaceful Minorca. Situated between France and Africa, the archipelago's islands each have distinct characters. Majorca is the most developed and offers a mass of hotels, fast food joints and crowded beaches. Ibiza is loved by a hard partying set, including many gay visitors. It is also increasingly popular with upscale travelers, drawn by the chameleon island's reputation as \"the new Provence.\" Pick an island and stake a claim on its sand.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.18/39.46/2.667");
        IslandChainModel bassIslands = new IslandChainModel("Bass Islands", canada, lakeErie, bassIslandsItinerary, bassIslandsPackList, "The Bass Islands are three American islands in the western half of Lake Erie. They are north of Sandusky, Ohio, and south of Pelee Island, Ontario.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#11.38/41.6727/-82.8273");
        IslandChainModel bermudaIsland = new IslandChainModel("Bermuda Islands", uk, atlanticOcean, bermudaIslandsItinerary, bassIslandsPackList, "Don’t be fooled by Bermuda’s small size; this 21-square-mile Atlantic island is big on history, personality and charm, from pink-sand beaches to historic forts. It’s known for aquatic adventures like shipwreck scuba diving, cliff jumping and deep-sea fishing. On land you’ll find an eclectic island culture of vibrant neighborhoods, brightly colored shorts and delicious fish chowder.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#10.03/32.2878/-64.7677");
        IslandChainModel caboVerdeIsland = new IslandChainModel("Cabo Verde", republicOfCaboVerde, atlanticOcean, caboVerdeIslandsItinerary, bassIslandsPackList, "Cape Verde or Cabo Verde, officially the Republic of Cabo Verde, is an archipelago and island country in the central Atlantic Ocean, consisting of ten volcanic islands with a combined land area of about 4,033 square kilometres", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.47/15.548/-23.935");
        IslandChainModel campanianIsland = new IslandChainModel("Campanian Archipelago", italy, tyrrhenianSea, genericItinerary, bassIslandsPackList, "Campania Island is an island on the coast of the Canadian province of British Columbia. It is located south of Prince Rupert, east across Hecate Strait from the Queen Charlotte Islands.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#8.68/40.6253/14.1745");
        IslandChainModel capriIsland = new IslandChainModel("Capri", italy, tyrrhenianSea, capriIslandsItinerary, bassIslandsPackList, "Capri is pure romance—dramatic views, the bluest ocean you’ve ever seen, even the scent of lemon blossoms in the air. The luminescent Blue Grotto, striking Faraglioni Rocks and the Palazzo al Mare are popular with travelers, but for a real treat, snorkel at Marina Piccola beach. It’s said to be the spot where Odysseus nearly succumbed to the Sirens’ song… a fitting legend for this alluring island.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#11.11/40.5452/14.2339");
        IslandChainModel chiloeIsland = new IslandChainModel("Chiloe", chile, pacificOcean, chiloeIslandsItinerary, bassIslandsPackList, "Although it's only a 30-minute ferry crossing away from mainland Chile across the Chacao Channel, verdant Isla Chiloe – the largest in the Chiloe archipelago – is another world. Sixteen wooden churches clustered around Castro on the island's east coast have UNESCO World Heritage status, and traditional palafitos (houses on stilts) dot its shores. To the west, Chiloe National Park shelters foxes, sea lions and otters and provides unspoiled terrain for horseback riding, sea kayaking and fishing.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#6.71/-42.658/-73.819");
        IslandChainModel corfuIsland = new IslandChainModel("Corfu", greece, ionianSea, corfuIslandsItinerary, bassIslandsPackList, "Corfu is studded with whitewashed houses, Byzantine churches, and the remains of Venetian fortresses and Greek temples. Wander the ancient streets of the Roman village of Kassiopi or explore the central Esplanade of the eponymous Corfu Town. For a DIY spa experience, lather yourself in mineral mud on the shore of the Canal D’Amour. Legend has it that the waterfalls of Nymphes used to attract the mythological beauties of the same name, who would flock to the village to bathe in the pristine waters.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.64/39.6228/19.8716");
        IslandChainModel creteIsland = new IslandChainModel("Crete", greece, aegeanSea, basicItinerary, bassIslandsPackList, "The birthplace of both the king of the Olympian gods and of modern European civilization, Crete is a Mediterranean jewel. It’s rich with archaeological and mythological history that’s reflected in its ancient ruins and cultural attractions. Soak up the charming atmosphere of Chania Town’s Old Venetian Harbor or the fortresses and monasteries of Rethymonon. The awesome Minoan ruins of Malia date to 1900 BC, and majestic Mt. Ida is said to be home to the cave where Zeus was born.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#6.62/35.173/24.893");
        IslandChainModel formenteraIsland = new IslandChainModel("Formentera", spain, mediterraneanSea, basicItinerary, bassIslandsPackList, "You may have to fly into Ibiza's airport to get to Formentera, but a vacation here is the antithesis of a wild week in Ibiza. You'll reach Formentera by ferry, and you'll find a quiet, peaceful little island with natural beauty to spare. Rent a scooter or bike to take you from beach to beach.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.07/38.7004/1.472");
        IslandChainModel galapagosIslands = new IslandChainModel("Galápagos Islands", ecuador, pacificOcean, genericItinerary, bassIslandsPackList, "Abundant wildlife above and below the waves draws eco-tourists to Ecuador's Galapagos. Get up close on a stroll or in a Zodiac boat. Snorkel and dive with denizens of the deep, from sea lions to sea turtles at Santiago's Cousin's Rock. Hike by finches, flamingos and iguanas along the Darwin Trail. Admire Sierra Negra Volcano on Isabela. As visitor numbers are limited within the islands' National Park, book your boat tour through a tour operator. Visit January through April for the best snorkeling.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.63/0.034/-90.377");
        IslandChainModel hawaiianIsland = new IslandChainModel("Hawaiian Islands", usa, pacificOcean, genericItinerary, bassIslandsPackList, "For many, the word \"vacation\" conjures images of sunbathing on a sunny beach, paddling in a dazzling blue ocean, napping under coconut trees—in other words, Hawaii. But travelers who can pull themselves away from the 50th state's stunning beaches will find so much more. From volcanic landscapes to hidden waterfalls and epic expeditions, a Hawaiian getaway can go in a dozen different directions. Each of the six major islands–Kauai, Oahu, Molokai, Lanai, Maui, and the island of Hawaii–has its own distinct personality and unique opportunities for adventure, dining, culture, and relaxation.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#5.55/19.731/-157.586");
        IslandChainModel heardMcDonaldIslands = new IslandChainModel("Heard Island and the McDonald Islands", australiaCountry, indianOcean, basicItinerary, bassIslandsPackList, "The Territory of Heard Island and McDonald Islands is an Australian external territory comprising a volcanic group of mostly barren Antarctic islands, about two-thirds of the way from Madagascar to Antarctica. The group's overall size is 372 km² in area and it has 101.9 km of coastline.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#8.22/-53.066/73.464");
        IslandChainModel hvarIsland = new IslandChainModel("Hvar", croatia, adriaticSea, basicItinerary, bassIslandsPackList, "As the island retreat of choice for European jetsetters and celebrities alike, it’s easy to see why Hvar grabs headlines. Sun-soaked beaches, lavender-scented hinterlands, and cobbled medieval towns provide a welcome change of pace from the seemingly endless choice of restaurants, bars, and nightclubs.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.22/43.177/16.4478");
        IslandChainModel ibizaIsland = new IslandChainModel("Ibiza", spain, mediterraneanSea, genericItinerary, bassIslandsPackList, "Ibiza: Old Spanish for \"party 'til you drop.\" Perhaps not literally, but this is definitely one of Europe's favorite nightlife playgrounds. Ibiza boasts more than 100 miles of coastline with some 50 beaches, plus plenty of restaurants, bars, and water sports—and clubs, of course. Fit in a little culture and visit Ibiza's UNESCO-designated old town.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.85/38.934/1.396");
        IslandChainModel iihaGrandeIsland = new IslandChainModel("Iiha Grande", brazil, atlanticOcean, bassIslandsItinerary, bassIslandsPackList, "Ilha Grande is one of Brazil’s most beautiful islands. The island is surrounded by pristine beaches, crystal clear waters, and an array of wildlife. To put it simply, Ilha Grande is an island paradise.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#9.34/-23.829/-45.3268");
        IslandChainModel ionianIslands = new IslandChainModel("The Ionian Islands", greece, ionianSea, genericItinerary, bassIslandsPackList, "The Ionian Islands are part of Greece and lie off the country’s west coast, in the Ionian Sea. The northernmost island, Corfu, has an old town with Renaissance, baroque and classical architecture. Corfu also features the 19th-century Liston, a promenade on the central square, with arcades and cafes. The 15th-century Old Fortress is nearby. The Palace of St. Michael and St. George is home to the Museum of Asian Art.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#7.62/38.056/20.906");
        IslandChainModel ischiaIsland = new IslandChainModel("Ischia", italy, tyrrhenianSea, bassIslandsItinerary, bassIslandsPackList, "Serving as the main port town for the island of the same name, the town of Ischia has been inhabited for centuries, famous for its beaches and the healing waters of its spas. The town is divided in two: Ischia Porto is the harbor district and commercial center of the island, filled with brightly lit taverns and bars, and Ischia Ponte, the historic quarter, with its ancient castle and its stone streets seemingly frozen in time.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#9.73/40.7305/13.9433");
        IslandChainModel islandsOfMadagascar = new IslandChainModel("Islands of Madagascar", madagascarCountry, indianOcean, basicItinerary, bassIslandsPackList, "Madagascar, officially the Republic of Madagascar, and previously known as the Malagasy Republic, is an island country in the Indian Ocean, approximately 400 kilometres off the coast of East Africa across the Mozambique Channel.", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#4.63/-19.15/45.99");
        IslandChainModel kauaiIsland = new IslandChainModel("Kauai", usa, pacificOcean, basicItinerary, bassIslandsPackList, "Perhaps more than any of the other islands, Kauai is known for its natural beauty and its dramatic, beautiful sites. These include Waimea Canyon, the Coconut Coast and much more. You'll find gorgeous mountains and waterfalls, white sand beaches, sugarcane fields, and beachside cliffs such as those on the Na Pali coast.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.56/22.0832/-159.515");
        IslandChainModel koSamuiIsland = new IslandChainModel("Koh Samui", thailand, gulfOfThailand, genericItinerary, bassIslandsPackList, "Once a fishing community, Koh Samui, Thailand's second largest island, has retained its charming sensibility. Spending time in Bophut is a wonderful way to soak up local culture; the beachy village restaurants and pubs are perfect spots to experience the sunset. There aren’t many other places where you can bask in the camp of a cabaret show and the serenity of a Buddhist temple. As far as the latter goes, Wat Plai Laem is a magnificent vision of gilded red rooftops and a massive spindly armed statue of Guanyin.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#9.65/9.4999/100.003");
        IslandChainModel mallorcaIsland = new IslandChainModel("Mallorca", spain, mediterraneanSea, bassIslandsItinerary, bassIslandsPackList, "Mallorca, also called Majorca, is the crown jewel of Spain’s Balearic Islands. The most popular destination the Mediterranean, Mallorca is known for its beautiful coastline, secluded coves, limestone mountains, Spanish architecture, wineries and fresh produce farms, and stunning beaches.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.57/39.536/2.929");
        IslandChainModel mauiIsland = new IslandChainModel("Maui", usa, pacificOcean, genericItinerary, bassIslandsPackList, "Stark volcanic landscapes, emerald valleys, and black-sand beaches—Maui really brings the drama. Sure, there are plenty of resorts and hotels here, but Maui never loses itself to tourism. Instead, it remains grounded in lush nature, Hawaiian culture, and aloha spirit. And seeing the sun rise from the summit of Haleakala or driving the Road to Hana will make even the most jaded traveler think this is paradise found.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.35/20.843/-156.341");
        IslandChainModel oahuIsland = new IslandChainModel("Oahu", usa, pacificOcean, basicItinerary, bassIslandsPackList, "Say aloha to tropical breezes, oceanfront luaus, and volcanic ridge-lines on Oahu, Hawaii’s most populated island. Follow in the footsteps of surfing forefather Duke Kahanamoku on Waikiki Beach, visit the royal quarters of Iolani Palace, and tour Pearl Harbor. Sample hot malasadas (local doughnuts) and shaved ice while shopping for vintage aloha shirts on Honolulu's Kapahulu Avenue. Then get off the tourist trail with a hike to Makapuu Lighthouse on the South Shore—a place so beautiful, it's been known to inspire more than a few proposals.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.52/21.5054/-157.9293");
        IslandChainModel philippinesIsland = new IslandChainModel("Philippines", philippinesCountry, southChinaSea, genericItinerary, bassIslandsPackList, "With more than 7,000 islands consisting of rice paddies, volcanos, mega-metropolises, world-class surf spots, and endemic wildlife, the Philippines is one of the most dazzling and diverse countries in all of Asia. Not to mention, it’s home to some of the world’s best beaches, too.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.79/11/122.92");
        IslandChainModel phuketIsland = new IslandChainModel("Phuket", thailand, gulfOfThailand, basicItinerary, bassIslandsPackList, "Tropical beaches, hidden temples, local markets, and a thumping club scene. Phuket draws those who mellow in the sun and thrive at night. Further inland, Phuket Town’s eateries allow you to dip into chili and blue ginger-spiced dishes, and a stroll through the old quarter opens a window into the layers of its past. Despite its size and geography, there’s plenty of dining, accommodations, and adventure to satisfy luxury travelers and budget-conscious trip takers all year long.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.51/7.996/98.431");
        IslandChainModel ponzaIsland = new IslandChainModel("Ponza", italy, tyrrhenianSea, bassIslandsItinerary, bassIslandsPackList, "The caves of Ponza are steeped in mystical mythology—legend has it that Ponza was Homer’s inspiration for the sorceress Circe’s island in The Odyssey. The whole island has a magical feel to it, from the grottoes to the botanical gardens to the underground labyrinth of Roman tunnels. Schedule a boat tour so that you can explore the entire island by sea—a truly spectacular experience.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.24/40.9038/12.9704");
        IslandChainModel praslinIsland = new IslandChainModel("Praslin Island", republicOfSeychelles, indianOcean, basicItinerary, bassIslandsPackList, "One of the Seychelles’ most popular destinations, Praslin is home to fantastic beaches and intimate hotels and resorts. Soak up the sun in style while you keep a sunglassed eye out for the very rare bird species that dwell on Praslin, including the Seychelles bulbul and the black parrot. Praslin National Park in the island's south contains the spectacular palm forest of Vallée de Mai. Divers love the ancient coral reefs off Praslin's shores.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#4.09/-5.98/50.55");
        IslandChainModel sanAndresIsland = new IslandChainModel("San Andres", colombia, caribbeanSea, genericItinerary, bassIslandsPackList, "The coral island of San Andres is a diverse ecosystem of reefs, geysers, groves, and cays. Needless to say, it’s perfect for diving, snorkeling, and outdoor exploring. This paradise has multicolored warm waters and 12 mangrove forests, and the beach cedars of Johnny Cay are like natural condos for beach birds. Keep an eye out for overlooked pirate treasure at Morgan’s Cave before chowing down on rondón, a signature Caribbean dish of fish, pork, conch, plantain and coconut milk.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.19/12.705/-81.587");
        IslandChainModel santoriniIsland = new IslandChainModel("Santorini Island", greece, aegeanSea, bassIslandsItinerary, bassIslandsPackList, "Even if you’ve never been to this Cyclades island in the Aegean Sea, you’d still recognize it immediately—its candy-colored houses carved into cliffs, sapphire waters, and chalk-white buildings topped with cobalt-blue domes. Roam the peaceful black-sand beaches or wander the streets of a provincial village like Imerovigli. Beautiful Oia is world famous for its sunsets, which seem to dial through a kaleidoscope of colors before fading to starlight.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.31/36.3991/25.4243");
        IslandChainModel ungujaIsland = new IslandChainModel("Unguja", tanzania, indianOcean, bassIslandsItinerary, bassIslandsPackList, "Zanzibar Island (Unguja) is the main island of Zanzibar. It’s well-known for historical Stone Town, beautiful beaches and nature, both on-land and the surrounding coral reefs.", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.63/-6.1226/39.3652");
        IslandChainModel andamanIsland = new IslandChainModel("Andaman Islands", india, indianOcean, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.36/11.858/92.75");
        IslandChainModel balearicIsland = new IslandChainModel("Balearic Islands", spain, ionianSea, bassIslandsItinerary, packList1, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.18/39.46/2.667");
        IslandChainModel bassIslands = new IslandChainModel("Bass Islands", canada, lakeErie, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#11.38/41.6727/-82.8273");
        IslandChainModel bermudaIsland = new IslandChainModel("Bermuda Islands", uk, atlanticOcean, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#10.03/32.2878/-64.7677");
        IslandChainModel caboVerdeIsland = new IslandChainModel("Cabo Verde", republicOfCaboVerde, atlanticOcean, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.47/15.548/-23.935");
        IslandChainModel campanianIsland = new IslandChainModel("Campanian Archipelago", italy, tyrrhenianSea, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#8.68/40.6253/14.1745");
        IslandChainModel capriIsland = new IslandChainModel("Capri", italy, tyrrhenianSea, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#11.11/40.5452/14.2339");
        IslandChainModel chiloeIsland = new IslandChainModel("Chiloe", chile, pacificOcean, bassIslandsItinerary, packList1, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#6.71/-42.658/-73.819");
        IslandChainModel corfuIsland = new IslandChainModel("Corfu", greece, ionianSea, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.64/39.6228/19.8716");
        IslandChainModel creteIsland = new IslandChainModel("Crete", greece, aegeanSea, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#6.62/35.173/24.893");
        IslandChainModel formenteraIsland = new IslandChainModel("Formentera", spain, mediterraneanSea, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.07/38.7004/1.472");
        IslandChainModel galapagosIslands = new IslandChainModel("Galápagos Islands", ecuador, pacificOcean, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#6.63/0.034/-90.377");
        IslandChainModel hawaiianIsland = new IslandChainModel("Hawaiian Islands", usa, pacificOcean, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#5.55/19.731/-157.586");
        IslandChainModel heardMcDonaldIslands = new IslandChainModel("Heard Island and the McDonald Islands", australiaCountry, indianOcean, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#8.22/-53.066/73.464");
        IslandChainModel hvarIsland = new IslandChainModel("Hvar", croatia, adriaticSea, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.22/43.177/16.4478");
        IslandChainModel ibizaIsland = new IslandChainModel("Ibiza", spain, mediterraneanSea, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.85/38.934/1.396");
        IslandChainModel iihaGrandeIsland = new IslandChainModel("Iiha Grande", brazil, atlanticOcean, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#9.34/-23.829/-45.3268");
        IslandChainModel ionianIslands = new IslandChainModel("The Ionian Islands", greece, ionianSea, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#7.62/38.056/20.906");
        IslandChainModel ischiaIsland = new IslandChainModel("Ischia", italy, tyrrhenianSea, bassIslandsItinerary, packList1, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#9.73/40.7305/13.9433");
        IslandChainModel islandsOfMadagascar = new IslandChainModel("Islands of Madagascar", madagascarCountry, indianOcean, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#4.63/-19.15/45.99");
        IslandChainModel kauaiIsland = new IslandChainModel("Kauai", usa, pacificOcean, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.56/22.0832/-159.515");
        IslandChainModel koSamuiIsland = new IslandChainModel("Koh Samui", thailand, gulfOfThailand, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#9.65/9.4999/100.003");
        IslandChainModel mallorcaIsland = new IslandChainModel("Mallorca", spain, mediterraneanSea, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.57/39.536/2.929");
        IslandChainModel mauiIsland = new IslandChainModel("Maui", usa, pacificOcean, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.35/20.843/-156.341");
        IslandChainModel oahuIsland = new IslandChainModel("Oahu", usa, pacificOcean, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#8.52/21.5054/-157.9293");
        IslandChainModel philippinesIsland = new IslandChainModel("Philippines", philippinesCountry, southChinaSea, bassIslandsItinerary, packList1, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#3.79/11/122.92");
        IslandChainModel phuketIsland = new IslandChainModel("Phuket", thailand, gulfOfThailand, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.51/7.996/98.431");
        IslandChainModel ponzaIsland = new IslandChainModel("Ponza", italy, tyrrhenianSea, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.24/40.9038/12.9704");
        IslandChainModel praslinIsland = new IslandChainModel("Praslin Island", republicOfSeychelles, indianOcean, bassIslandsItinerary, packList5, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#4.09/-5.98/50.55");
        IslandChainModel sanAndresIsland = new IslandChainModel("San Andres", colombia, caribbeanSea, bassIslandsItinerary, packList3, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#7.19/12.705/-81.587");
        IslandChainModel santoriniIsland = new IslandChainModel("Santorini Island", greece, aegeanSea, bassIslandsItinerary, packList2, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.31/36.3991/25.4243");
        IslandChainModel ungujaIsland = new IslandChainModel("Unguja", tanzania, indianOcean, bassIslandsItinerary, packList4, "SUMMARY_HERE", "https://api.mapbox.com/styles/v1/mbarkley23/cky2c4rxe1pu815nzdmq48ta6.html?title=copy&access_token=pk.eyJ1IjoibWJhcmtsZXkyMyIsImEiOiJja3kyYzIyY2Qwamt4MzN0NWt5N2lhdWswIn0.rxZNbrc8-0SzQlOABDaubQ&zoomwheel=true&fresh=true#10.63/-6.1226/39.3652");
        IslandChainModel seychelles = new IslandChainModel("Seychelles",republicOfSeychelles,indianOcean,bassIslandsItinerary,packList4,"Adventure Summary Coming Soon","https://api.mapbox.com/styles/v1/cstephens/cky2cwav41al814o5n98c52su.html?title=false&access_token=pk.eyJ1IjoiY3N0ZXBoZW5zIiwiYSI6ImNreTJjc2tzYjBqbXQydW1wZ2N0a20zeDYifQ.SkbSfO39uFF6KHu0Jm7ISA&zoomwheel=false#8.45/-4.481/55.582");
        islandChainRepo.save(andamanIsland);
        islandChainRepo.save(balearicIsland);
        islandChainRepo.save(bassIslands);
        islandChainRepo.save(bermudaIsland);
        islandChainRepo.save(caboVerdeIsland);
        islandChainRepo.save(campanianIsland);
        islandChainRepo.save(capriIsland);
        islandChainRepo.save(chiloeIsland);
        islandChainRepo.save(corfuIsland);
        islandChainRepo.save(creteIsland);
        islandChainRepo.save(formenteraIsland);
        islandChainRepo.save(galapagosIslands);
        islandChainRepo.save(hawaiianIsland);
        islandChainRepo.save(heardMcDonaldIslands);
        islandChainRepo.save(hvarIsland);
        islandChainRepo.save(ibizaIsland);
        islandChainRepo.save(iihaGrandeIsland);
        islandChainRepo.save(ionianIslands);
        islandChainRepo.save(ischiaIsland);
        islandChainRepo.save(islandsOfMadagascar);
        islandChainRepo.save(kauaiIsland);
        islandChainRepo.save(koSamuiIsland);
        islandChainRepo.save(mallorcaIsland);
        islandChainRepo.save(mauiIsland);
        islandChainRepo.save(oahuIsland);
        islandChainRepo.save(philippinesIsland);
        islandChainRepo.save(phuketIsland);
        islandChainRepo.save(ponzaIsland);
        islandChainRepo.save(praslinIsland);
        islandChainRepo.save(sanAndresIsland);
        islandChainRepo.save(santoriniIsland);
        islandChainRepo.save(ungujaIsland);
        islandChainRepo.save(seychelles);
    }
}